# Generated by Django 4.2 on 2023-10-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
